# Generated by Django 3.0 on 2020-09-15 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('age_size', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('pwithd', models.IntegerField()),
                ('pwithoutd', models.IntegerField()),
                ('discount', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('main_img', models.ImageField(upload_to='postpics/%Y/%m/%d/')),
                ('img_1', models.ImageField(blank=True, upload_to='postpics/%Y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='postpics/%Y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='postpics/%Y/%m/%d/')),
                ('shipin_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
