# Generated by Django 3.0 on 2020-09-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneix', '0002_watche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('select', models.CharField(max_length=500)),
                ('cancel', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
